import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { useState, useMemo } from "react";
import { Post } from "../Post";
import { BlogPostCard } from "@/components/BlogPostCard";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { FeaturedPost } from "@/components/FeaturedPost";
import { SecondaryPostsColumn } from "@/components/SecondaryPostsColumn";
import { AdBanner } from "@/components/AdBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export type Category = {
  slug: string;
  name: string;
};

export type HomeTemplateProps = {
  posts: Post[];
  categories: Category[];
  postsByCategory: Record<string, Post[]>;
  showAdBanner: boolean;
};

function splitPosts(posts: Post[]) {
  const sorted = [...posts].sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  );
  const [latestPost, ...remaining] = sorted;
  return {
    latestPost,
    secondaryPosts: remaining.slice(0, 3),
    gridPosts: remaining.slice(3),
  };
}

export default function HomeTemplate({
  posts,
  categories,
  postsByCategory,
  showAdBanner
}: HomeTemplateProps) {
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);

  // Posts da categoria selecionada (ou todos, sem ads)
  const activePosts = useMemo(() => {
    const base = selectedCategory
      ? (postsByCategory[selectedCategory] ?? [])
      : posts.filter((p) => !p.ad);

    return base.filter((p) => !p.ad);
  }, [selectedCategory, posts, postsByCategory]);

  const { latestPost, secondaryPosts, gridPosts } = useMemo(
    () => splitPosts(activePosts),
    [activePosts]
  );

  // Últimas 4 categorias que possuem ao menos 1 post relacionado
  const visibleCategories = [...categories]
    .reverse()
    .filter((cat) => (postsByCategory[cat.slug]?.length ?? 0) > 0)
    .slice(0, 4);

  return (
    <>
      <Head>
        <title>Blog Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`min-h-screen ${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main>
          <section className="py-8 md:py-12 pt-10 md:pt-16">
            <div className="container mx-auto px-4 md:px-8">
              <div className="mb-8 md:mb-10">
                <h1 className="text-2xl md:text-3xl font-bold text-slate-900 dark:text-white">
                  Bem-vindo à Evalue Insights
                </h1>
                <p className="mt-3 text-sm md:text-base text-slate-600 dark:text-slate-400 leading-relaxed max-w-3xl">
                  Aqui você encontra conteúdo estratégico para fortalecer sua
                  presença digital, conectar-se com profissionais do setor e
                  inspirar decisões com insights relevantes para empresas de
                  tecnologia.
                </p>
              </div>

              {/* ── Filtro por categoria ── */}
              <div className="flex flex-wrap gap-2 mb-8">
                {/* Botão "Todos" sempre primeiro */}
                <button
                  onClick={() => setSelectedCategory(null)}
                  className={`px-4 py-2 rounded-full border text-sm font-medium transition-colors
                    ${
                      selectedCategory === null
                        ? "border-slate-900 dark:border-slate-300 bg-slate-900 dark:bg-slate-800 text-white"
                        : "border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700"
                    }`}
                >
                  Todos
                </button>

                {/* Últimas 4 categorias vindas do servidor */}
                {visibleCategories.map((cat) => (
                  <button
                    key={cat.slug}
                    onClick={() => setSelectedCategory(cat.slug)}
                    className={`px-4 py-2 rounded-full border text-sm font-medium transition-colors
                      ${
                        selectedCategory === cat.slug
                          ? "border-slate-900 dark:border-slate-300 bg-slate-900 dark:bg-slate-800 text-white"
                          : "border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700"
                      }`}
                  >
                    {cat.name}
                  </button>
                ))}
              </div>

              {/* ── Nenhum resultado ── */}
              {activePosts.length === 0 && (
                <p className="text-slate-500 dark:text-slate-400 text-sm py-12 text-center">
                  Nenhum post encontrado para esta categoria.
                </p>
              )}

              {/* ── "Todos": destaque + secundários + grid ── */}
              {selectedCategory === null && activePosts.length > 0 && (
                <>
                  {latestPost && (
                    <section className="grid grid-cols-1 md:grid-cols-[3fr_2fr] gap-4 items-stretch">
                      <FeaturedPost {...latestPost} />
                      {secondaryPosts.length > 0 && (
                        <SecondaryPostsColumn posts={secondaryPosts} />
                      )}
                    </section>
                  )}

                  {/* ── Banner de anúncio ── */}
                  {showAdBanner && <AdBanner />}

                  {gridPosts.length > 0 && (
                    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mt-4 md:mt-8">
                      {gridPosts.map((post, index) => (
                        <div
                          key={post.slug}
                          className="animate-fade-in"
                          style={{ animationDelay: `${index * 100}ms` }}
                        >
                          <BlogPostCard {...post} />
                        </div>
                      ))}
                    </div>
                  )}
                </>
              )}

              {/* ── Categoria específica: somente grid ── */}
              {selectedCategory !== null && activePosts.length > 0 && (
                <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mt-8">
                  {activePosts.map((post, index) => (
                    <div
                      key={post.slug}
                      className="animate-fade-in"
                      style={{ animationDelay: `${index * 100}ms` }}
                    >
                      <BlogPostCard {...post} />
                    </div>
                  ))}
                </div>
              )}
            </div>
          </section>
        </main>
        <Footer />
      </div>
    </>
  );
}