import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { Post } from "../Post";
import { BlogPostCard } from "@/components/BlogPostCard";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { FeaturedPost } from "@/components/FeaturedPost";
import { SecondaryPostsColumn } from "@/components/SecondaryPostsColumn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export type HomeTemplateProps = {
  posts: Post[]
}

function AdBanner() {
  return (
    <div className="w-full my-6 lg:my-10">
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-[#075985] via-[#0369a1] to-[#0e7490] p-4 sm:p-5 md:p-8 shadow-lg">

        {/* Grid background */}
        <div className="absolute inset-0 opacity-10 pointer-events-none">
          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="ad-grid" width="20" height="20" patternUnits="userSpaceOnUse">
                <path
                  d="M 20 0 L 0 0 0 20"
                  fill="none"
                  stroke="#ffffff"
                  strokeWidth="1"
                />
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#ad-grid)" />
          </svg>
        </div>

        {/* Label */}
        <span className="absolute top-3 right-4 text-[10px] font-medium text-white/40 uppercase tracking-widest">
          Anúncio
        </span>

        {/* Content */}
        <div className="relative z-10 flex items-center justify-between gap-4">

          {/* Left */}
          <div className="min-w-0 flex-1">
            <h2 className="text-white text-sm sm:text-base md:text-xl font-bold tracking-wide uppercase leading-tight m-0">
              Potencialize sua Presença Tech
            </h2>

            <p className="text-cyan-100 text-[12px] sm:text-sm md:text-base mt-1 md:mt-2 mb-0 font-light leading-snug md:leading-relaxed">
              Conecte-se com especialistas e tomadores de decisão.
            </p>
          </div>

          {/* Right */}
          <div className="shrink-0">
            <a
              href="/anuncie"
              className="inline-flex items-center justify-center whitespace-nowrap bg-[#facc15] hover:bg-[#eab308] text-[#0f172a] font-bold text-[10px] sm:text-xs md:text-sm uppercase tracking-wider px-3 sm:px-4 md:px-6 py-2.5 md:py-3 rounded-xl transition-all duration-200 hover:-translate-y-0.5 shadow-md no-underline"
            >
              Anuncie
            </a>
          </div>

        </div>
      </div>
    </div>
  );
}

export default function HomeTemplate({ posts }: HomeTemplateProps) {
  const postsWithoutAds = posts.filter(post => !post.ad);
  const sortedPosts = postsWithoutAds.sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  );
  const [latestPost, ...remainingPosts] = sortedPosts;
  const secondaryPosts = remainingPosts.slice(0, 3);
  const gridPosts = remainingPosts.slice(3);

  return (
    <>
      <Head>
        <title>Blog Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`min-h-screen ${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        <main>
          <section className="py-8 md:py-12 pt-10 md:pt-16">
            <div className="container mx-auto px-4 md:px-8">
              {/* rounded-3xl border-slate-200/80 dark:border-slate-700/80 bg-gray/70 dark:bg-slate-900/80 shadow-sm backdrop-blur-sm max-w-3xl p-6 pl-0 */}
              <div className="mb-8 md:mb-10">
                <h1 className="text-2xl md:text-3xl font-bold text-slate-900 dark:text-white">
                  Bem-vindo à EvalueTech Insights
                </h1>
                <p className="mt-3 text-sm md:text-base text-slate-600 dark:text-slate-400 leading-relaxed max-w-3xl">
                  Aqui você encontra conteúdo estratégico para fortalecer sua presença digital, conectar-se com profissionais do setor e inspirar decisões com insights relevantes para empresas de tecnologia.
                </p>
              </div>

              {/* ── Filtro por categoria ── */}
              <div className="flex flex-wrap gap-2 mb-8">
                <button className="px-4 py-2 rounded-full border border-slate-300 dark:border-slate-600 bg-slate-900 dark:bg-slate-800 text-white text-sm font-medium hover:bg-slate-800 dark:hover:bg-slate-700 transition-colors">
                  Todos
                </button>
                <button className="px-4 py-2 rounded-full border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                  Tecnologia & Inovação
                </button>
                <button className="px-4 py-2 rounded-full border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                  Marketing
                </button>
                <button className="px-4 py-2 rounded-full border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                  Vendas
                </button>
                <button className="px-4 py-2 rounded-full border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                  Gestão de Projetos
                </button>
              </div>

              {/* ── Seção de destaque ── */}
              {latestPost && (
                <section className="grid grid-cols-1 md:grid-cols-[3fr_2fr] gap-6 items-stretch">
                  <FeaturedPost {...latestPost} />
                  <SecondaryPostsColumn posts={secondaryPosts} />
                </section>
              )}

              {/* ── Banner de anúncio ── */}
              {/* <AdBanner /> */}

              {/* ── Grid de posts ── */}
              <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mt-8">
                {gridPosts
                  .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
                  .map((post, index) => (
                    <div
                      key={post.slug}
                      className="animate-fade-in"
                      style={{ animationDelay: `${index * 100}ms` }}
                    >
                      <BlogPostCard {...post} />
                    </div>
                  ))}
              </div>

            </div>
          </section>
        </main>
        <Footer />
      </div>
    </>
  );
}