import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { Post } from "../Post";
import { BlogPostCard } from "@/components/BlogPostCard";
import { Header } from "@/components/Header";
// import TextUnderlineRound from "@/components/text-underline-round";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export type HomeTemplateProps = {
  posts: Post[]
}

export default function HomeTemplate({ posts }: HomeTemplateProps) {
  const postsWithoutAds = posts.filter(post => !post.ad);
  // const lastPost = postsWithoutAds[postsWithoutAds.length - 1];

  return (
    <>
      <Head>
        <title>Brand Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`min-h-screen bg-background ${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main>
          {/* <HeaderTemplate /> */}
          {/* <HighlightSection lastPost={lastPost} /> */}
          {/* <PostsList posts={posts} /> */}
          <section className="py-16 md:py-24">
            <div className="container mx-auto px-4 md:px-8">
              <div className="text-center space-y-4 mb-12 md:mb-16">
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl text-foreground">
                  Explore Conteúdos Que Inspiram
                </h2>
                <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                  Descubra, Aprenda e Conecte-se com Conteúdos Feitos pra Você
                </p>
              </div>
              
              <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                {postsWithoutAds.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()).map((post, index) => (
                  <div 
                  key={post.slug} 
                  className="animate-fade-in"
                  style={{ animationDelay: `${index * 100}ms` }}
                  >
                  <BlogPostCard {...post} />
                  </div>
                ))}
              </div>
            </div>
          </section>
        </main>
        <footer className="backdrop-blur-lg bg-background/80 border-t border-border py-12">
          <div className="container mx-auto px-4 md:px-8">
            <div className="flex flex-col md:flex-row justify-between items-center gap-4">
              <div className="flex items-center gap-2">
                <span className="text-sm text-muted-foreground">
                  © 2024 MindTech. Todos os direitos reservados.
                </span>
              </div>
              <div className="flex gap-6">
                <a href="/sobre-nos" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                  Sobre Nós
                </a>
                <a href="/anuncios" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                  Jobs
                </a>
                <a href="/contato" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                  Contato
                </a>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </>
  )
}
